#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 13 16:56:45 2019

@author: matthew
"""
import sys
import getopt
from gcis import gcis


def main():
    try:
        args = sys.argv[1:]
        HELP_MESSAGE = """\
        Usage:
            gcis-cli [argument]
            -h help
            -i initialize
            -u [local/db]
                local: update local ghcn files
                db: update Postgres GCIS database
            -r [simple/full]
                simple: drop GCIS schema and rebuild (without data load)
                full: drop GCIS schema, rebuild, and reload data to tables (will not update local repository).
        """
        gcis_instance = gcis()
        if str(args[0]) == '-h':
            print(HELP_MESSAGE)

        elif str(args[0]) == '-i':
            gcis_instance.init()

        elif args[0] == '-u':
            if args[1] == 'local':
                gcis_instance.update_local_ghcn()
            elif args[1] == 'db':
                gcis_instance.update_db()

        elif args[0] == '-r':
            if args[1] == 'simple':
                gcis_instance.rebuild_simple()
            elif args[1] == 'full':
                gcis_instance.rebuild_full()  # populate tables

    except getopt.error as argError:
        print(str(argError))
        print(HELP_MESSAGE)
        print('arg')

    except IndexError:
        print(HELP_MESSAGE)

    except KeyboardInterrupt:
        print(' Process killed by user')


if __name__ == "__main__":
    main()
